/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sonoro.ui;

import com.sonoro.model.Member;
import com.sonoro.model.MemberUpdateListener;

/**
 *
 * @author ryanl
 */
public class EditMemberDialog extends javax.swing.JDialog {

    private MemberUpdateListener memberUpdateListener;
    
    public EditMemberDialog(java.awt.Frame parent, boolean modal, Member memberCopy) {
        super(parent, modal);
        initComponents();
        nameField.setText(memberCopy.getName());
        emailField.setText(memberCopy.getEmail());
    }
    
    public void setMemberUpdateListener(MemberUpdateListener memberUpdateListener)
    {
        this.memberUpdateListener = memberUpdateListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sonoro - Edit Member");

        titleLabel.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        titleLabel.setText("Edit Member Information");
        getContentPane().add(titleLabel, java.awt.BorderLayout.PAGE_START);

        bottomPanel.setLayout(new java.awt.GridLayout(1, 2));

        confirmButton.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(confirmButton);

        clearButton.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(clearButton);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        centerPanel.setLayout(new java.awt.GridLayout(4, 1));

        nameLabel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        nameLabel.setText("Name");
        centerPanel.add(nameLabel);

        nameField.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        centerPanel.add(nameField);

        emailLabel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        emailLabel.setText("Email Address");
        centerPanel.add(emailLabel);

        emailField.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        centerPanel.add(emailField);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        memberUpdateListener.memberUpdated(nameField.getText(), emailField.getText());
        this.dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        nameField.setText(null);
        emailField.setText(null);
    }//GEN-LAST:event_clearButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
