/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sonoro.ui;

import com.sonoro.model.Settings;
import com.sonoro.model.SettingsUpdateListener;
import javax.swing.JOptionPane;

/**
 *
 * @author ryanl
 */
public class SettingsDialog extends javax.swing.JDialog {

    private SettingsUpdateListener settingsUpdateListener;
    private Settings settings;
    
    public SettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.settings = Settings.getInstance();
        if (settings.isInitialized())
        {
            emailUsernameTextField.setText(settings.getEmailUsername());
            emailPasswordField.setText(new String(settings.getEmailPassword()));
        }
    }
    
    public void setSettingsUpdateListener(SettingsUpdateListener settingsUpdateListener)
    {
        this.settingsUpdateListener = settingsUpdateListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButton = new javax.swing.JButton();
        settingsLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        emailUsernameLabel = new javax.swing.JLabel();
        emailUsernameTextField = new javax.swing.JTextField();
        emailPasswordLabel = new javax.swing.JLabel();
        emailPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sonoro - Settings");

        saveButton.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        saveButton.setText("Save");
        saveButton.setPreferredSize(new java.awt.Dimension(100, 40));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, java.awt.BorderLayout.PAGE_END);

        settingsLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        settingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsLabel.setText("Settings");
        settingsLabel.setPreferredSize(new java.awt.Dimension(67, 40));
        getContentPane().add(settingsLabel, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        emailUsernameLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        emailUsernameLabel.setText("Email Username:");
        emailUsernameLabel.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(emailUsernameLabel);

        emailUsernameTextField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel1.add(emailUsernameTextField);

        emailPasswordLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        emailPasswordLabel.setText("Email Password:");
        jPanel1.add(emailPasswordLabel);

        emailPasswordField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel1.add(emailPasswordField);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (emailUsernameTextField.getText().length() <= 0 || emailPasswordField.getPassword().length <= 0)
        {
            JOptionPane.showMessageDialog(this, "Please enter all fields.", "Error", HEIGHT);
        }
        else
        {            
            settings.setEmailUsername(emailUsernameTextField.getText());
            settings.setEmailPassword(emailPasswordField.getPassword());
            settings.setInitialized(true);
            settingsUpdateListener.settingsUpdated(settings);
            dispose();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField emailPasswordField;
    private javax.swing.JLabel emailPasswordLabel;
    private javax.swing.JLabel emailUsernameLabel;
    private javax.swing.JTextField emailUsernameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel settingsLabel;
    // End of variables declaration//GEN-END:variables
}
